version: "3.9"
services:
  fe-dev:
    # front end development server
    profiles:
      - all
      - fe-dev
    build:
      context: fe/
      dockerfile: docker/fe-dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./fe/:/app/fe
    environment:
      - BROWSER=none
      - REACT_APP_BE_URI=http://localhost:<PORT>/graphql
  be-dev:
    # back end development server
    profiles:
      - all
      - be-dev
    depends_on:
      - db-dev
    build:
      context: be/
      dockerfile: docker/be-dev.dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./be/:/app/be
    environment:
      - DATABASE_IP=db-dev
      - DATABASE_PORT=5432
      - SERVER_PORT=3000
  db-dev:
    # development database
    profiles:
      - all
      - db-dev
      - adminer # include '--profile adminer' in your docker command to launch adminer alongside db
      - be-dev
    image: postgres:13 # Uses Debian, use 'postgres:13-alpine' for lighter version
    restart: always
    ports:
      - 7842:5432
    volumes:
      # database persistance location
      - ./docker/volumes/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_IP=127.0.0.1
      - DATABASE_PORT=7842
      - SERVER_PORT=4501

  adminer:
    # adminer, so you don't have to install a database manager
    profiles:
      - all
      - adminer # include '--profile adminer' in your docker command to launch adminer alongside db
    image: adminer:4.8.0
    depends_on:
      - db-dev
    restart: always
    ports:
      - 8080:8080
