version: '3.9'
services:
  prod:
    # production server
    build:
      context: ./
      dockerfile: docker/prod.dockerfile
    ports:
      - 80:4501
      - 443:4501
    volumes:
      - ./:/app
    environment:
      # Back end environment variables
      - DATABASE_IP=127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SERVER_PORT=4501
      # Front end environment variables
      - BROWSER=none
      - ESLINT_NO_DEV_ERRORS=true
