version: '3.9'
services:
  prod:
    # production server
    build:
      context: ./
      dockerfile: docker/prod.dockerfile
    ports:
      - 80:4501
      - 443:4501
    volumes:
      - ./:/app
    environment:
      # Back end environment variables
      - SERVER_PORT=4501
      - DATABASE_IP=$RDS_HOSTNAME
      - DATABASE_PORT=$RDS_PORT
      #- DATABASE_USER=$RDS_USER
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=$RDS_PASSWORD
      - DATABASE_NAME=$RDS_DB_NAME
      # Front end environment variables
      - BROWSER=none
      - ESLINT_NO_DEV_ERRORS=true
